CREATE TABLE person(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	firstName VARCHAR(60),
	lastName VARCHAR(100),
	email VARCHAR(200),
	phoneNr VARCHAR(20),
	pictureURL MEDIUMTEXT
);


CREATE TABLE item(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(200),
	description MEDIUMTEXT,
	pictureURL MEDIUMTEXT,
	websiteURL MEDIUMTEXT,
	price DOUBLE
);
