CREATE TABLE person(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	firstName VARCHAR(60),
	lastName VARCHAR(100),
	email VARCHAR(200),
	phoneNr VARCHAR(20),
	pictureURL MEDIUMTEXT
);


CREATE TABLE item(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(200),
	description MEDIUMTEXT,
	pictureURL MEDIUMTEXT,
	websiteURL MEDIUMTEXT,
	price DOUBLE
);

CREATE TABLE gift(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	giverID INTEGER, 
	recepientID INTEGER, 
	itemID INTEGER,
	quantity INTEGER,
	CONSTRAINT giverID_FK FOREIGN KEY (giverID) REFERENCES person(id) 
		ON DELETE SET NULL 
		ON UPDATE CASCADE,
	CONSTRAINT recepeientID_FK FOREIGN KEY (recepientID) REFERENCES person(id) 
		ON DELETE SET NULL 
		ON UPDATE CASCADE,
	CONSTRAINT itemID_FK FOREIGN KEY (itemID) REFERENCES item(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
