package com.strandlie.lambda.addperson;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

import exceptions.DatabaseErrorException;
import exceptions.InvalidCreateRequestFormatException;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;


public class AddPersonAPIHandler extends APIHandler {
	

    @Override
    public PersonResponse handleRequest(PersonRequest request, Context context) {
        context.getLogger().log("Received create request with values: \n" + request.toString() + "\n");

		PersonResponse response = new PersonResponse();
		response.setPersonIsAdded(false);
		
		String firstName = request.getFirstName();
		String lastName = request.getLastName();
		if (firstName == null) {
			throw new InvalidCreateRequestFormatException("firstName");
		}
		else if (lastName == null) { throw new InvalidCreateRequestFormatException("lastName");
		}
		
		String email = request.getEmail();
		String phoneNr = request.getPhoneNr();
		String pictureURL = request.getPictureURL();
		
		try {
			int id = createInDatabase(firstName, lastName, email, phoneNr, pictureURL);
			response.setId(id);
			response.setPersonIsAdded(true);
			}
		catch (SQLException e) {
			response.setErrorMessage(e.toString());
			context.getLogger().log("Database error: " + e.toString());
			// Using RuntimeException to be able to return the error through the API
			throw new DatabaseErrorException("Could not add the person to the database", e.toString());
		}
		context.getLogger().log("\nCreate request successfully processed\n");
		
		return response;
    }
    
	
	private int createInDatabase(String firstName, String lastName, String email, String phoneNr, String pictureURL) throws SQLException  {
		
		String sql = "INSERT INTO person (firstName, lastName, email, phoneNr, pictureURL)" +
					  "VALUES(?, ?, ?, ?, ?)";
		connection = DriverManager.getConnection(
						"jdbc:" + System.getenv("DBDriver") + ":" + System.getenv("DBPath"),
						System.getenv("DBUsername"),
						System.getenv("DBPassword"));
		
		connection.setCatalog(System.getenv("DBDatabase"));

		PreparedStatement statement = connection.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);
		setStringOrNull(1, firstName, statement);
		setStringOrNull(2, lastName, statement);
		setStringOrNull(3, email, statement);
		setStringOrNull(4, phoneNr, statement);
		setStringOrNull(5, pictureURL, statement);
		statement.executeUpdate();
		
		// Gets the key generated by the DB for the object inserted
		ResultSet generatedKeys =  statement.getGeneratedKeys();
		
		if (generatedKeys.next()) {
			int id = generatedKeys.getInt(1);
			connection.close();
			return id;
		}
		connection.close();
		return -1;
	}
}
