language: java
jdk:
        - oraclejdk8
sudo: false
script:
    cd Lambda/Eclipse/lambda-workspace/
    mvn test -f personHandlers/pom.xml $MAVEN_CLI_OPTS
notifications:
    email: false

after_success:
    - bash <(curl -s https://codecov.io/bash)
