CREATE TABLE person(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	firstName VARCHAR(60),
	lastName VARCHAR(100),
	email VARCHAR(200),
	phoneNr VARCHAR(20),
	pictureURL MEDIUMTEXT
);


CREATE TABLE item(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(200),
	description MEDIUMTEXT,
	pictureURL MEDIUMTEXT,
	websiteURL MEDIUMTEXT,
	price DOUBLE
);

CREATE TABLE gift(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	giverID INTEGER, 
	recepientID INTEGER, 
	itemID INTEGER,
	quantity INTEGER,
	CONSTRAINT giverID_FK FOREIGN KEY (giverID) REFERENCES person(id) 
		ON DELETE SET NULL 
		ON UPDATE CASCADE,
	CONSTRAINT recepientID_FK FOREIGN KEY (recepientID) REFERENCES person(id) 
		ON DELETE SET NULL 
		ON UPDATE CASCADE,
	CONSTRAINT itemID_FK FOREIGN KEY (itemID) REFERENCES item(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE wish(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	wisherID INTEGER, 
	itemID INTEGER,
	quantity INTEGER,
	CONSTRAINT wisherID_FK FOREIGN KEY (wisherID) REFERENCES person(id) 
		ON DELETE SET NULL 
		ON UPDATE CASCADE,
	CONSTRAINT itemID_FK FOREIGN KEY (itemID) REFERENCES item(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE giftGroup(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100),
	description MEDIUMTEXT,
	pictureURL MEDIUMTEXT
);

CREATE TABLE personInGiftGroup(
	personID INTEGER, 
	groupID INTEGER,
	CONSTRAINT personInGroup_PK PRIMARY KEY(personID, groupID),
	CONSTRAINT personID_FK FOREIGN KEY (personID) REFERENCES person(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT groupID_FK FOREIGN KEY (groupID) REFERENCES giftGroup(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);